### ISSUE TITLE
Is this puppet module still maintained ?

### ISSUE THREAD

**Issue by daisukixci** [Accenture/hiera-aws-sm#5]
It seems to not work with latest puppet version, Is it still maintained ?

**Comment by cedriclecoz** [comment]
Hi, 
Just did a fresh deploy of a puppet server, so all up to date on oss puppet, I didn't have any problem getting creds from AWS SM.

**Comment by daisukixci** [comment]
On a pe enterprise server and even though the gem looks installed and I have 
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Function Load Error for function 'hiera_aws_sm': [hiera-aws-sm] Must install aws-sdk-core gem to use hiera-aws-sm backend (file: /etc/puppetlabs/code/environments/development/site-modules/profile/manifests/security/datadog_main.pp, line: 55, column: 3) on node REDACTED
```

my hiera.yaml is 
```
---
version: 5

defaults:
  datadir: "data"

hierarchy:
  - name: "AWS SSM"
    lookup_key: hiera_aws_sm
    options:
      continue_if_not_found: true
      region: us-east-1
  - name: "Yaml backend"
    data_hash: yaml_data
    paths:
      - "nodes/%{trusted.certname}.yaml"
      - "common.yaml"
```

and I have this 
```
package {'aws-sdk':
    ensure   => present,
    provider => puppetserver_gem
  }
```
 running on puppet main server. Am I missing something ?
